### ISSUE TITLE
Información sobre el rol del SCRUM MASTER (1er rol del Scrum)

### ISSUE THREAD

**Issue by TinchoGarcia** [TinchoGarcia/2022-06-Proyecto-Integrador#13]

**Comment by Aranthiel** [comment]
![rol_scrumMaster](https://user-images.githubusercontent.com/39966971/171087976-0d55c8b1-8bbf-4510-a5d3-5d8f7c8fdc85.jpg)

Responsabilidades del Scrum Master:
PLANIFICAR las implementaciones junto con la organizacióm
AYUDAR a la organizacion a entender cuales son las interacciones que aportan valor y cuales no 
AYUDAR al PO a entender las metodoñogías ágiles y a maximizar el valor del negocio
AYUDAR al equipo de desarrollo a convertirse en auto-organizado y multifuncional
AYUDAR a que se lleven a cabo las posibles mejoras detectadas eln la retrospectiva del sprint.
ENSEÑAR al PO a priorizar y gestionar efectivamente el Product Backlog.
ACTUALIZAR el burndow chart junto con el equipo
SOLUCIONAR los impedimentos que se presenten durante el srpint
ASEGURAR que haya una definicion de DONE
PROMOVER buenas prácticas de programación

**Comment by Aranthiel** [comment]
El Scrum Master es el encargado de asegurar que la metodología se lleve a cabo tal y como está definida. Esto se logra haciendo que cada persona del equipo entienda la teoría y práctica de la metodología.

La persona con el rol de Scrum Master sirve al equipo de Scrum de varias formas:

    ●       Orienta a los miembros del equipo en la autogestión y la multifuncionalidad.
    ●       Ayuda a los equipos a enfocarse en crear incrementos de alto valor que cumplan con la definición de Terminado.
    ●       Remueve los impedimentos de progreso que pudiera tener el equipo.
    ●       Asegura que todos los eventos de Scrum se lleven a cabo y que sean positivos, productivos y dentro de los tiempos establecidos.

El Scrum Master también colabora con el propietario del producto de las siguientes maneras:

    ●       Ayuda a encontrar técnicas para definir efectivamente el objetivo del producto y la gestión de la pila de producto.
    ●       Ayuda a que los miembros del equipo entiendan los artículos de la pila de producto.
    ●       Ayuda a establecer un planeamiento del producto de manera empírica para entornos que sean complejos.

Finalmente también colabora con el resto de la organización con actividades como:

    ●       Liderar, planear y entrenar a los miembros de la organización en lo que respeta a la adopción de Scrum .
    ●       Planear y aconsejar cómo implementar Scrum dentro de la organización.
    ●       Ayudar a los empleados a comprender y llevar a cabo la práctica de la metodología, mediante un enfoque empírico para trabajos complejos.

**Comment by Aranthiel** [comment]
Durante la reunión de planificación de Sprint, el Scrum Master deberá desempeñar las siguientes funciones:

    ●       Realizar esta reunión antes de cada Sprint .
    ●       Asegurar que se cuenta con una pila de producto preparada por el propietario del producto.
    ●       Ayudar a mantener el diálogo entre el propietario del producto y los desarrolladores.
    ●       Asegurar que se llegue a un acuerdo entre el propietario del producto y los desarrolladores con respecto a lo que incluirá el incremento.
    ●       Ayudar a comprender la visión y las necesidades de negocio del cliente.
    ●       Asegurar que se ha realizado una descomposición y estimación del trabajo realistas.
    ●       Asegurar que al final de la reunión estén determinados los siguientes puntos:

            Los ítems de la pila de producto que se van a ejecutar
            El objetivo del Sprint .
            La pila de Sprint con todas las tareas estimadas.
            La duración del Sprint y la fecha de reunión de revisión.
            La definición de Terminado que determinará que el incremento está listo.
