### ISSUE TITLE
Crear archivo con conceptos Fundamentales de Materia "Ingles"

### ISSUE THREAD

**Issue by FedeGonzalez2016** [TinchoGarcia/2022-06-Proyecto-Integrador#23]

**Comment by AgustinBen** [comment]
## Lecto-comprensión

# Previewing (previsualización) e hipótesis de lectura
No leemos el texto entero; prestamos atención al TITULO, SUBTITULOS, IMAGENES y AL TEXTO QUE ACOMPAÑA LAS IMAGENES, para saber de qué se trata.

# Estrategias de Lectura: Skimming and Scanning

** Skimming **→ es un “vistazo”. Consiste en leer solo PARTES del texto, buscando ideas principales (primer y último párrafo).
** Scanning **→ Pasamos la vista por el texto buscando información específica.

---------------------------------------------------------------------------------------------------------------------------------------------------------------

## El Sustantivo

 I. El Sustantivo o Nombre: Es aquel tipo de palabras cuyo significado determina la realidad. Esto es, los sustantivos nombran todas las cosas: personas, objetos, sensaciones, sentimientos, ideas, etc. 
Algunas clases de sustantivos son: 
1. contable (coche) / incontable (leche) 
2. propio (Juan) / común (pan) 
3. simple (puerta) / compuesto (lavacoches) 
4. concreto (almacén) / abstracto (belleza) 
Sustantivar: se trata de convertir cualquier categoría gramatical en un sustantivo: cantar (verbo) / cante (sustantivo).

## El Pronombre
II. El Pronombre: Es la palabra que sustituye a otros términos que designan personas o cosas en un momento determinado.
Ejemplo: quiero a Laura / la quiero.
Clases de pronombres:
1. Personales: yo, tú, él , nosotros, vosotros, ellos: me, te, se, nos, os, lo, mi, ti, si, le, lo, la...
2. Demostrativos: este, ese, aquel, estos, esos, aquellos...
3. Indefinidos: nada, todo, algo, nadie, alguien, alguno, bastantes, varios, cualquier, cualquiera, cualesquiera...
4. Numerales: un, dos, tres, primero, segundo...
5. Relativos: que, quien, cuyo, cual, cuantos...
6. Posesivos: mío, tuyo, suyo, nuestro, vuestro, suyo...
7. Interrogativos: qué, quién, cuánto, cuándo, cuál, dónde, cómo...
Pronominalizar: se trata de sustituir una palabra por un pronombre (lo, la, le): le di un beso / se lo di; le conté una historia / se la conté.

## El Adjetivo
El Adjetivo: Es la palabra que acompaña al nombre para determinarlo o calificarlo:
Ej.: el coche rojo / esa casa está lejos.
Grados del adjetivo:
1. positivo: Este es un postre dulce.
2. comparativo: este postre es más dulce que aquel.
3. superlativo: este es un postre muy dulce / dulcísimo.
Clases de adjetivos:
1. especificativos: aquellos que indican una cualidad propia del sustantivo. Ej.; el coche rojo
2. explicativos: aquellos que redundan en una cualidad del nombre. Ej.: la nieve blanca
Clases de adjetivos determinativos:
1. demostrativos: (este, ese, aquel)
2. posesivos: (mi, tu, su, nuestra, vuestra, sus)
3. indefinidos: (algún, ningún, otro, varios, cierto, bastante, demasiado, cualquier, todo, cada, etc.)
4. numerales: (dos, segundo, etc.)
5. interrogativos: (qué, cuántos, etc.)
6. exclamativos: (qué, cuántos, etc.) 
 (Algunas de estas palabras eran pronombres si iban solos, pero con un nombre son adjetivos)
 
## El Verbo
IV. El Verbo: Parte de la oración que se conjuga y expresa acción y estado. 
Los tiempos verbales se dan en tres Modos: Indicativo, Subjuntivo e Imperativo. 
Los Tiempos son: 
1. Simples: Presente, Pretérito imperfecto, Pretérito perfecto simple, Futuro imperfecto, Condicional... 
2. Compuestos: Pretérito perfecto compuesto, Pretérito anterior, Futuro perfecto, Pretérito pluscuamperfecto, Condicional perfecto... 
Formas no personales: Las formas no personales no presentan desinencia de número y persona. Son el infinitivo: cantar; el gerundio: cantando; y el participio: cantado.

## El Adverbio
V. El Adverbio: es una parte invariable de la oración que puede modificar, matizar o determinar a un verbo, un adjetivo o a otro adverbio. 

Clases de adverbios. 

1. lugar: lejos, cerca, aquí, allí, allá, acá… 

2. modo: así, bien, mal, etc. 

3. tiempo: ayer, mañana, nunca, hoy, jamás, siempre, a veces. 

4. duda: quizás, tal vez, acaso. 

5. cantidad: mucho, poco, bastante, demasiado. 

6. afirmación: sí, también. 

7. negación: no, tampoco.

## La Preposición y conjunción
 La preposición: es una categoría gramatical invariable, que no tiene significado propio y que sirve para relacionar términos. 

Clases de preposiciones: a, ante, bajo, cabe, con, contra, de, desde, en, entre, hacia, hasta, para, por, según, sin, so, sobre, tras

 La conjunción: es una categoría gramatical invariable -parecida a la preposición-, que se utiliza para unir palabras y oraciones 

Clases de conjunciones:

1. Copulativas: y, e, ni. 

2. Disyuntivas: o, u. 

3. Adversativas: pero, mas, sino. 

4. Concesiva: aunque. 

5. Causales: porque, pues, 

6. Condicionales: si. 

7. Comparativa: tan, tanto, que, como. 

8. Consecutivas: tanto, que, luego. 

9. Concesivas: aunque. 

10. Finales: para. 

11. Completiva: que, si. 



Locución conjuntiva: se trata de un grupo de palabras que equivalen a una conjunción (uno de sus miembros es una conjunción). Las hay del mismo tipo que las conjunciones. Ejemplos: sin embargo, de que, ya que, puesto que, con tal que, hasta el punto de que, a fin de que, tanto que, si bien, por más que, para que, etc.
