### ISSUE TITLE
Subir un script SQL que constará de la creación de una base de datos con sus tablas.

### ISSUE THREAD

**Issue by TinchoGarcia** [TinchoGarcia/2022-06-Proyecto-Integrador#47]
![Diagrama Peluqueria Canina](https://user-images.githubusercontent.com/106358263/184059662-f67ea245-5d5a-40ab-ab8b-62baa0b89e7c.JPG)

La Base de Datos refiere a una Peluquería Canina.

**Comment by Aranthiel** [comment]
RESUELTO POR MARTIN GARCIA

-- crear la tabla Dueño
CREATE TABLE Dueno
(
DNI int not null,
Nombre_Dueno varchar(25) not null,
Apellido varchar(25) not null,
Telefono varchar(15) not null,
Direccion varchar(50) not null,
CONSTRAINT Iddueno Primary Key (DNI)
);


-- 1. Realice la consulta correspondiente para crear la tabla Perro, teniendo en cuenta sus claves foráneas y primarias. 

CREATE TABLE Perro
(
ID_Perro int not null,
Nombre_Perro varchar(25) not null,
Fecha_nac date not null, 
Sexo varchar(10) not null,
DNI_dueno int not null,
CONSTRAINT Idperro Primary Key(ID_Perro),
CONSTRAINT Fdnidueno Foreign Key(DNI_dueno) REFERENCES Dueno(DNI)
);

-- Crear la tabla Historial
CREATE TABLE Historial
(
ID_Historial int not null,
Fecha Date not null,
Perro int not null,
Descripcion varchar(50) not null,
Monto float not null,
CONSTRAINT Idhistorial Primary Key(ID_Historial),
CONSTRAINT Fperro Foreign Key(Perro) REFERENCES Perro(ID_Perro) 
);
